FROM python:3.12-slim

# Create stdconfig directory
WORKDIR /

# dependencies needed for ARMv6/7 builds
RUN apt update
RUN apt install build-essential ninja-build  python-numpy cmake -y
RUN pip install --upgrade pip && \
    pip install --upgrade setuptools && \
    #apt install cmake libxml2-dev libxslt-dev libffi libffi-dev g++ gcc musl-dev rust cargo openssl-dev && \
    pip install paho-mqtt astral ip2geotools scikit-learn 
# && \
#    apk del openssl-dev libffi-dev xz-dev libxml2-dev libxslt-dev openssl-dev linux-headers musl-dev gcc rust cargo && \
#    rm -rf /root/.cache/ && \
#    rm -rf /var/cache/apk/*

ENTRYPOINT ["python"]
